name: Model Testing

on:
  pull_request:
    branches: [test]
  push:
    branches: [test]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install xgboost numpy pandas scikit-learn
          
      - name: Run Tests
        run: |
          # python -m unittest discover -s tests -p 'test_model.py'
          if [ -d "tests" ]; then
          python -m unittest discover -s tests -p 'test_model.py'
          else
          echo "No tests directory found. Skipping tests."
          exit 0
          fi


